name: Scheduled Event GitHub Processor

on:
  schedule:
    # CloseAddressedIssues - test, schedule is every 5 minutes
    - cron: '*/5 * * * *'
    # LockClosedIssues - test, schedule is every 6 minutes
    - cron: '*/6 * * * *'
# This removes all unnecessary permissions, the ones needed will be set below.
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions: {}

jobs:
  event-handler:
    permissions:
      issues: write
      pull-requests: write
    name: Handle ${{ github.event.schedule }} ${{ github.event.action }} event
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Close Addressed Issues scheduled event
        if: github.event.schedule == '*/5 * * * *'
        run: |
          echo $GITHUB_PAYLOAD > payload.json
          dotnet run -- ${{ github.event_name }} payload.json CloseAddressedIssues
        shell: bash
        working-directory: tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor
        env:
          GITHUB_PAYLOAD: ${{ toJson(github.event) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: LockClosedIssues scheduled event
        if: github.event.schedule == '*/6 * * * *'
        run: |
          echo $GITHUB_PAYLOAD > payload.json
          dotnet run -- ${{ github.event_name }} payload.json LockClosedIssues
        shell: bash
        working-directory: tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor
        env:
          GITHUB_PAYLOAD: ${{ toJson(github.event) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
